version: '3.8'
name: 'akmalandikaakso'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8084:80"
    networks:
      - web_network
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf  
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:latest
    env_file:
      - ./mysql/.env  
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - web_network
    volumes:
      - ./mysql/custom.conf:/etc/mysql/conf.d/custom.cnf  
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  
      - mysql_data:/var/lib/mysql  
    configs:
      - source: mysql_custom_conf
        target: /etc/mysql/conf.d/custom.cnf  
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      
  redis:
    image: redis:latest  
    ports:
      - "6378:6379"  
    networks:
      - web_network  
    healthcheck:  
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3


  
  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phpmyadmin_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
  # webservice
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8087:80"
    networks:
      - app-network
    depends_on:
      - mariadb

networks:
  app-network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  mariadb_data: {}
  mysql_data: {}

configs:
  nginx_default_conf:
    file: ./nginx/default.conf  
  mysql_custom_conf:
    file: ./mysql/custom.conf  


